### PR TITLE
Updated tests

### PR DESCRIPTION
**Pull request by mattmoses1**
…Updated tests to adjust for recent changes in WHOIS data.

### CODE REVIEW

**Comment by mikemaccana** [comment]
I don't see any modules being uopgraded, just new unused ones being added as a dependency. What do the new modules do?

Also can you use string.includes rather than string indexof substring does not equal -1? Thanks.

**Comment by mattmoses1** [comment]
Updated.

**Comment by mattmoses1** [comment]
You're right. Oversight on my part. It's actually one of the whois-json's
dependencies that use those modules which need to be updated. I'll revert
those changes as well as make your other suggestion.

**Comment by mattmoses1** [comment]
The final test is failing but I think it's due to latency with geektools.com's whois lookup.

**Pull request merged**
